import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class ErasingCharacters:
    def simulate(self, s):
        ns = list(s)
        while True:
            did = 0
            for i in range(1, len(ns)):
                if ns[i] == ns[i-1]:
                    ns.pop(i)
                    ns.pop(i - 1)
                    did = 1
                    break
            if not did:
                break
        return ''.join(ns)

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, hasAnswer, p1):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str("\"") + str(p0) + str("\""))
	print(str("]"))
	obj = ErasingCharacters()
	startTime = time.clock()
	answer = obj.simulate(p0)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		print(str("Desired answer:"))
		print(str("\t") + str("\"") + str(p1) + str("\""))
	
	print(str("Your answer:"))
	print(str("\t") + str("\"") + str(answer) + str("\""))
	if (hasAnswer):
		res = answer == p1
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = "cieeilll"
p1 = "cl"
all_right = (disabled or KawigiEdit_RunTest(0, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = "topcoder"
p1 = "topcoder"
all_right = (disabled or KawigiEdit_RunTest(1, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = "abcdefghijklmnopqrstuvwxyyxwvutsrqponmlkjihgfedcba"
p1 = ""
all_right = (disabled or KawigiEdit_RunTest(2, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = "bacaabaccbaaccabbcabbacabcbba"
p1 = "bacbaca"
all_right = (disabled or KawigiEdit_RunTest(3, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 4 -----
disabled = False
p0 = "eel"
p1 = "l"
all_right = (disabled or KawigiEdit_RunTest(4, p0, True, p1) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))
	
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# Fox Ciel received a string as a birthday present. However, the string was too long for her, so she decided to make it shorter by erasing some characters.
# 
# 
# The erasing process will look as follows:
# 
# Find the smallest i such that the i-th character and the (i+1)-th character of the string are same.
# If there is no such i, end the process.
# Remove the i-th and the (i+1)-th character of the string, and repeat from 1.
# 
# 
# 
# For example, if she receives "cieeilll", she will change the string as follows: "cieeilll" -> "ciilll" -> "clll" -> "cl". You are given a string s. Return the string she will get after she erases characters as described above.
# 
# DEFINITION
# Class:ErasingCharacters
# Method:simulate
# Parameters:string
# Returns:string
# Method signature:def simulate(self, s):
# 
# 
# CONSTRAINTS
# -s will contain between 1 and 50 characters, inclusive.
# -Each character in s will be a lowercase letter ('a'-'z').
# 
# 
# EXAMPLES
# 
# 0)
# "cieeilll"
# 
# Returns: "cl"
# 
# This is the example from the statement.
# 
# 1)
# "topcoder"
# 
# Returns: "topcoder"
# 
# She won't erase any characters at all.
# 
# 2)
# "abcdefghijklmnopqrstuvwxyyxwvutsrqponmlkjihgfedcba"
# 
# Returns: ""
# 
# 
# 
# 3)
# "bacaabaccbaaccabbcabbacabcbba"
# 
# Returns: "bacbaca"
# 
# 
# 
# 4)
# "eel"
# 
# Returns: "l"
# 
# 
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
